name: DeepRL-testing
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - conda-forge
dependencies:
  - python==3.10.13
  - openssl
  - absl-py
  - asttokens
  - ca-certificates
  - cloudpickle
  - comm
  - _libgcc_mutex==0.1
  - _openmp_mutex==4.5
  - bzip2
  - contourpy
  - cycler
  - debugpy
  - decorator
  - evdev
  - exceptiongroup
  - executing
  - farama-notifications
  - filelock
  - fonttools
  - fsspec
  - grpcio
  - gym
  - gym-notices
  - importlib-metadata
  - iniconfig
  - ipykernel
  - ipython
  - jax-jumpy
  - jedi
  - jinja2
  - jupyter_client
  - jupyter_core
  - kiwisolver
  - krb5
  - ld_impl_linux-64
  - libedit
  - libffi
  - libgcc
  - libgcc-ng
  - libgomp
  - libsodium
  - libstdcxx
  - libstdcxx-ng
  - libuuid
  - markdown
  - markupsafe
  - matplotlib
  - matplotlib-inline
  - mpmath
  - ncurses
  - nest-asyncio
  - networkx
  - numpy
  - packaging
  - pandas
  - parso
  - pexpect
  - pickleshare
  - pillow
  - pip
  - platformdirs
  - pluggy
  - prompt-toolkit
  - protobuf
  - psutil
  - ptyprocess
  - pure_eval
  - pybullet
  - pygame
  - pygments
  - pynput
  - pyparsing
  - pytest
  - python-dateutil
  - python-xlib
  - python_abi
  - pytz
  - pyzmq
  - readline
  - scipy
  - setuptools
  - six
  - sqlite
  - stack_data
  - sympy
  - tensorboard
  - tensorboard-data-server
  - tk
  - tomli
  - tornado
  - traitlets
  - transforms3d
  - triton
  - typing_extensions
  - tzdata
  - wcwidth
  - werkzeug
  - wheel
  - xz
  - zeromq
  - zipp
  - zlib
  - black
  - pip:
      - ale-py==0.10.1
      - annotated-types==0.7.0
      - bullet-safety-gym==1.4.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - cloudpickle==3.1.1
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - filelock==3.17.0
      - fonttools==4.55.8
      - git+https://github.com/liuzuxin/fsrl.git@main
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glfw==2.8.0
      - gymnasium
      - h5py==3.13.0
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - jinja2==3.1.5
      - kiwisolver==1.4.8
      - llvmlite==0.44.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mujoco==2.3.3
      - networkx==3.4.2
      - noise==1.2.2
      - numba==0.61.0
      - numpy==1.24.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opencv-python==4.11.0.86
      - pettingzoo==1.24.3
      - pillow==11.1.0
      - prettytable==3.7.0
      - proglog==0.1.10
      - protobuf==3.19.6
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygame==2.1.0
      - pyopengl==3.1.9
      - pyparsing==3.2.1
      - pyrallis==0.3.1
      - python-dotenv==1.0.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - rich==13.9.4
      # - safety-gymnasium==1.0.0
      - sentry-sdk==2.24.1
      - setproctitle==1.3.5
      - six==1.17.0
      - smmap==5.0.2
      - stable-baselines3==2.3.2
      - sb3-contrib
      - sympy==1.13.1
      - tianshou==0.5.1
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - typing-inspect==0.9.0
      - tzdata==2025.1
      - urllib3==2.3.0
      - wandb==0.19.8
      - xmltodict==0.14.2

